[package]
name = "tb_core"
version = "0.1.0"
authors = ["dahai-f <1119369173@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.4"
rayon = "1.5.0"

[dev-dependencies]
rand = "0.8.3"
